name: Build docker test stage and push dev to DockerHub - dev
on:
  push:
    branches:
      - dev
jobs:
  docker_test_stage:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to DockerHub
      uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

    - name: Build the Docker image and push
      uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:docker"
          plattforms: linux/amd64,linux/arm64,linux/arm/v6
          push: false
          tags: ${{ secrets.DOCKERHUB_USERNAME}}/sdp:test
          target: test




