name: Build docker test stage and push dev to DockerHub - dev
on:
  push:
    branches:
      - dev
jobs:
  docker_test_stage:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Build and test Docker image
      uses: actions/docker/cli@v2
      with:
        args: build -t my-image-dev .
        push: false
    - name: Push to Docker Hub
      if: github.event_name == 'push'
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: my-docker-username/my-image-dev

