name: Build docker test stage

on:
  push:
    branches: [ "feature" ]

jobs:
  docker_test_stage:
    runs-on: ubuntu-latest

    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Test Docker image
      uses: docker/build-push-action@v3
      with:
        platforms: linux/amd64, linux/arm/v6
        push: false
        tags: mlpl/sdp_project:test
        target: test
