name: Build docker test stage and push prod to DockerHub - main

on:
  push:
    branches:
      - 'main'

jobs:

  docker_test_stage:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)


